Linter logic

diff --git a/.github/workflows/bump_version.yml b/.github/workflows/bump_version.yml
--- a/.github/workflows/bump_version.yml
+++ b/.github/workflows/bump_version.yml
@@ -1,45 +1,101 @@
 name: Bump version
 
-on:
+on: 
   pull_request:
-    types:
-      - closed
+      branches: [ master ]
      
 concurrency:
     group: ${{ github.workflow }}-${{ github.ref }} 
     cancel-in-progress: true
  
 jobs:
-  bump:
-    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'bump'
+  linter:
     runs-on: ubuntu-latest
+    env:
+      LocalCommit:  ${{ github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
+      PRBODY: ${{ github.event.pull_request.body }} 
   
     steps:
+      - name : Deduce bump mode from PR description
+        run: |
+          PRBODY_CLEAN=$(echo "$PRBODY" | tr -d '\r')
+          echo "----- PRBODY DEBUG START -----"
+          echo $PRBODY_CLEAN | cat -vte
+          echo "----- PRBODY DEBUG END -------"
+          
+          major=$(echo "$PRBODY_CLEAN" | grep -iE "^\s*-\s*\[x\]\s*Break \(major\)" | wc -l)
+          minor=$(echo "$PRBODY_CLEAN" | grep -iE "^\s*-\s*\[x\]\s*Feature \(minor\)" | wc -l)
+          patch=$(echo "$PRBODY_CLEAN" | grep -iE "^\s*-\s*\[x\]\s*Bug fix \(patch\)" | wc -l)
+          nobump=$(echo "$PRBODY_CLEAN" | grep -iE "^\s*-\s*\[x\]\s*No source changes \(no version change\)" | wc -l)
+  
+  
+          echo $major
+          echo $minor
+          echo $patch
+          echo $nobump
+  
+          echo $((major + minor + patch + nobump)) 
+  
+          if [[ $((major + minor + patch + nobump)) -eq 1 ]]; then
+            if [[ $((major)) -eq 1 ]]; then 
+              echo "bumpmode="major" >> $GITHUB_OUTPUT
+            fi
+            if [[ $((minor)) -eq 1 ]]; then 
+              echo "bumpmode="minor" >> $GITHUB_OUTPUT
+            fi
+            if [[ $((patch)) -eq 1 ]]; then 
+              echo "bumpmode="patch" >> $GITHUB_OUTPUT
+            fi
+            if [[ $((nobump)) -eq 1 ]]; then 
+              echo "bumpmode="nobump" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "Invalid version bump selected."
+            exit 1
+          fi 
+
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          ref: ${{ github.event.pull_request.base.ref }}
+          ref: ${{ github.head_ref }}
+          repository: ${{ github.event.pull_request.base.repo.full_name }}
+      - run: git fetch origin $GITHUB_BASE_REF
 
-      - name: Determine bump type
-        id: determine_bump
-        run: |
-          BUMP_TYPE="patch"
-          if [[ "${{ github.event.pull_request.labels[*] }}" == *"major"* ]]; then
-            BUMP_TYPE="major"
-          elif [[ "${{ github.event.pull_request.labels[*] }}" == *"minor"* ]]; then
-            BUMP_TYPE="minor"
-          fi
-          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
+      - name: Set Branch name
+        id: branch-name
+        run:
+          echo "branchName=$GITHUB_BASE_REF" >> $GITHUB_OUTPUT
 
-      - name: Bump version
-        id: bump
+      - name: Get old version
         run: |
           README="README.md"
           CMAKE="CMakeLists.txt"
           prefix="Program: BSMPT version "
 
-          OLD_VERSION=$(grep --color=never "${prefix}" "${README}" | sed -e "s/${prefix}//g" | tr -d '\r')
+          BASE_VERSION=$(grep --color=never "${prefix}" "${README}" | sed -e "s/${prefix}//g" | tr -d '\r')
+          echo "Base version is: $BASE_VERSION"
 
+          if [[ $((BASE_VERSION)) -eq "" ]]; then 
+            echo "Could not retrieve base version"
+            exit 1
+          fi
+
+          echo "OLD_VERSION=$BASE_VERSION" >> $GITHUB_OUTPUT
+
+      - name: Define base git diff args
+        id: git-diff-args
+        run: |
+          echo "args=origin/${{steps.branch-name.outputs.branchName}}..HEAD" >> $GITHUB_OUTPUT
+          
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.head_ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+
+      - name: Bump version
+        id: bump
+        run: |
           IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
 
           case "${{ steps.determine_bump.outputs.bump_type }}" in
@@ -58,7 +114,13 @@ jobs:
 
           sed -i -e "s/Program: BSMPT version ${OLD_VERSION}/Program: BSMPT version ${NEW_VERSION}/g" "$README"
           sed -i -e "s/set(BSMPT_VERSION ${OLD_VERSION})/set(BSMPT_VERSION ${NEW_VERSION})/g" "$CMAKE"
-              
+
+      - name: Check if we have local changes
+        id: check-changes
+        shell: bash
+        run: |
+          if [[ -z $(git status --porcelain --untracked-files=no) ]]; then echo "ChangesFound=False" >> $GITHUB_OUTPUT; else echo "ChangesFound=True" >> $GITHUB_OUTPUT; fi
+
       - name: setup git config
         run: |
           # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
@@ -66,7 +128,14 @@ jobs:
           git config user.email "<>"
 
       - name: Commit changes
+        if: steps.check-changes.outputs.ChangesFound == 'True' && env.LocalCommit == 'true'
         run: |
-          # Push version bump
-          git commit -am "Version bumped"
+          git commit -am "Automatic version bump"
           git push
+
+      - name: Notify that changes are required
+        if: ${{ steps.check-changes.outputs.ChangesFound == 'True' && env.LocalCommit != 'true' }}
+        run: |
+          echo "Version changes are required" >> $GITHUB_STEP_SUMMARY
+          exit 1
+
