Fix identation 2

diff --git a/.github/workflows/executables.yml b/.github/workflows/executables.yml
--- a/.github/workflows/executables.yml
+++ b/.github/workflows/executables.yml
@@ -76,20 +76,20 @@ jobs:
       if: runner.os != 'Windows'
 
     - name: Check if executables were created
-    run: |
-        $exe = Get-ChildItem .\build\*\bin\BSMPT.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
-        if (-not $exe) {
-          Write-Error "Executable not found."
-          exit 1
-        }
+      run: |
+          $exe = Get-ChildItem .\build\*\bin\BSMPT.exe -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
+          if (-not $exe) {
+            Write-Error "Executable not found."
+            exit 1
+          }
 
-        $output = & $exe --help
-        if ($output -like '*BSMPT calculates the strength of the electroweak phase transition*') {
-          Write-Host "Executable found and verified."
-          exit 0
-        }
-        else {
-          Write-Error "Executable output did not match expected string."
-          exit 1
-        }
-    if: runner.os == 'Windows'
+          $output = & $exe --help
+          if ($output -like '*BSMPT calculates the strength of the electroweak phase transition*') {
+            Write-Host "Executable found and verified."
+            exit 0
+          }
+          else {
+            Write-Error "Executable output did not match expected string."
+            exit 1
+          }
+      if: runner.os == 'Windows'
