Dont use secret in dependabot job

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -11,13 +11,22 @@ concurrency:
 jobs:
   linter:
     runs-on: ubuntu-latest
+    env:
+      LocalCommit: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]' }}
   
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
           ref: ${{ github.head_ref }}
+        if: env.LocalCommit
+
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.head_ref }}
           token: ${{ secrets.LINTER_PAT }}
+        if: !env.LocalCommit
 
       - name: Install clang-format
         if: inputs.apply_clang_format
@@ -59,8 +68,14 @@ jobs:
           git config user.email "<>"
 
       - name: Commit changes
-        if: steps.check-changes.outputs.ChangesFound == 'True'
+        if: steps.check-changes.outputs.ChangesFound == 'True' && env.LocalCommit
         run: |
           git commit -am "Automatically applied linter"
           git push
+
+      - name: Notify that changes are required
+        if: steps.check-changes.outputs.ChangesFound == 'True' && !env.LocalCommit
+        run: |
+          echo "Linter changes are required" >> $GITHUB_STEP_SUMMARY
+          exit 1
 
